.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/enhancement_request.md, .github/pull_request_template.md
Adapt the templates more precisely for the project
=> GitHub templates update

.ci/docs-gen, .ci/pipeline_definitions, Makefile
Generate command-line reference docs on release.
=> Generate cmd reference docs on release

pkg/reactor/document_worker.go, pkg/reactor/download_controller.go, pkg/resourcehandlers/github/github_resource_handler.go, pkg/resourcehandlers/resource_handlers.go
Fixes #88 
```improvement user
Fixed an issue with silent download fail in the specific case of GitHub resource with correct path and wrong resource name.
```
=> fix silent download fail for incorrect url

.ci/pipeline_definitions
=> Fixed docs step input

README.md, docs/index.md, docs/manifest-ref.md, docs/manifests.md, docs/user-index.md, pkg/api/types.go
Improve and amend the documentation about manifests.
/priority critical
=> Manifest documentation

pkg/reactor/gitinfo_controller.go
Introduces RW lock on the map that may be used concurrently in the git info controller
Fixes #121
=> Fix concurrent map writes

pkg/jobs/controller.go, pkg/jobs/controller_test.go, pkg/jobs/jobs.go, pkg/jobs/jobs_test.go, pkg/jobs/workqueue.go, pkg/reactor/content_processor.go, pkg/reactor/document_controller.go, pkg/reactor/download_controller.go, pkg/reactor/gitinfo_controller.go
Adding a couple of synchronization mutexes in order to prevent race conditions that were discovered using the Golang tool "race".
=> Adds mutex to shared resources between workers.

pkg/markdown/html_links.go, pkg/reactor/content_processor_test.go
Changes the way reference links are extracted from HTML sources
Fixes # 172
```noteworthy user
```
=> Fix html link references

pkg/resourcehandlers/git/git_resource_handler.go, pkg/resourcehandlers/git/repository.go
Previously nodesSelector were not resolved correctly because they were consider as a pointer to another Documentation structure
Fixes #
```noteworthy user
```
=> Fix nodesSelector resolution for Git ResourceHandler

go.mod, go.sum, pkg/reactor/content_processor.go, pkg/reactor/content_processor_test.go
Discover broken links when building absolute links
Closes #185 
@swilen-iwanow 
```noteworthy user
None
```
=> Discover broken links when building absolute links

.ci/pipeline_definitions
Post release notes in gardener-documentation slack channel
Fixes #
```noteworthy operator
The release notes will be posted in `gardener-documentation` channel
```
=> Post release notes in gardener-documentation slack channel

pkg/api/nodes.go, pkg/api/nodes_test.go, pkg/api/types.go, pkg/hugo/processor.go, pkg/markdown/html_links.go, pkg/reactor/content_processor.go, pkg/reactor/content_processor_test.go, pkg/reactor/reactor.go, pkg/resourcehandlers/github/github_resource_handler.go, pkg/resourcehandlers/github/github_resource_handler_test.go, pkg/resourcehandlers/testhandler/test_resource_handler.go
- extends node relative path in the scope of the api.Documentation
- rewrite md links with hugo url front matter property
- rewrite html links to embedded images to their raw format
Fixes #197 
```noteworthy user
```
=> Fixing link resolve for links that point to the website & html image links

pkg/resourcehandlers/git/git_resource_handler.go
Change file types of the tree leafs from `tree` to `blob`.
In this way the Non-page files e.g. (images, pdfs, etc.) will have valid absolute path.
Fixes #
@dimitar-kostadinov 
```noteworthy user
None
```
=> Change file types of the tree leafs from tree to blob

pkg/reactor/reactor.go
On file name collision, docforge will return an error
Fixes #
```noteworthy user
```
=> On file name collision, docforge will return an error

cmd/app/cmd.go, cmd/app/completion.go, cmd/app/factory.go, cmd/configuration/configuration.go, cmd/configuration/types_configuration.go, pkg/api/nodes.go, pkg/api/parser.go, pkg/git/git.go, pkg/git/types.go, pkg/hugo/fswriter.go, pkg/jobs/jobs.go, pkg/mock/git/git.go, pkg/processors/document.go, pkg/reactor/content_processor.go, pkg/reactor/document_worker.go, pkg/reactor/downloader.go, pkg/reactor/github_info.go, pkg/reactor/manifest_resolver.go, pkg/reactor/validator.go, pkg/reactor/validator_test.go, pkg/resourcehandlers/fs/fs.go, pkg/resourcehandlers/git/git_resource_handler.go, pkg/resourcehandlers/git/git_resource_handler_test.go, pkg/resourcehandlers/git/repository.go, pkg/resourcehandlers/github/github_resource_handler.go, pkg/resourcehandlers/github/github_utils.go, pkg/resourcehandlers/github/gitinfo.go, pkg/resourcehandlers/github/gitinfo_test.go, pkg/resourcehandlers/github/resource_locator_cache.go, pkg/util/httpclient/client.go
Fixes  Golint issues
Fixes #
```noteworthy user
```
=> Fix Golint issues

.ci/build, .ci/check, .ci/docs-gen, .ci/docs-lint, .ci/integration-test, .ci/test
Fixes #
```noteworthy user
```
=> Fix shell checks

pkg/resourcehandlers/git/git_resource_handler.go, pkg/resourcehandlers/github/github_resource_handler.go
Fixes duplication of some blogs
Fixes #245
```noteworthy user
Removes duplicate blogs at https://gardener.cloud/blog/ 
```
=> Fix blogs duplication

.ci/check-manifest, .ci/pipeline_definitions, .docforge/manifest.yaml, Makefile
This PR will be reverted after the all of the check pass
Fixes #
```noteworthy user
None
```
=> [TEST PR] Add docforge manifest and check-manifest script

cmd/app/cmd.go, pkg/api/parser.go, pkg/api/types.go, pkg/reactor/build.go, pkg/reactor/content_processor_test.go, pkg/reactor/manifest_resolver.go, pkg/reactor/manifest_resolver_test.go, pkg/reactor/reactor.go, pkg/reactor/validator.go, pkg/resourcehandlers/git/git_resource_handler.go, pkg/resourcehandlers/git/git_resource_handler_test.go, pkg/resourcehandlers/github/github_resource_handler.go, pkg/resourcehandlers/resource_handlers.go, pkg/resourcehandlers/resourcehandlersfakes/fake_resource_handler.go
Adds support for relative paths in manifests
Fixes #
```noteworthy user
Adds support for relative paths in manifests
```
=> Resolve relative paths in manifests

pkg/reactor/content_processor.go
Avoids links to container nodes that do not contains index file
Fixes #
```noteworthy user
None
```
=> Avoid links to container nodes that do not contains index file

.ci/integration-test, cmd/app/cmd.go, cmd/app/factory.go, cmd/app/manifest.go, pkg/api/parser.go, pkg/api/parser_test.go, pkg/reactor/content_processor_test.go, pkg/resourcehandlers/git/git_resource_handler.go, pkg/resourcehandlers/git/git_resource_handler_test.go, pkg/resourcehandlers/github/github_resource_handler.go, pkg/resourcehandlers/github/github_resource_handler_test.go
This PR changes the configuration of the parser.go file
```improvement developer
Change in parser configuration
```
=> Parser reconfiguration

cmd/app/cmd.go, pkg/reactor/content_processor.go
Remove redundant validation of relative links
Fixes #
```noteworthy user
None
```
=> Remove redundant validation of relative links

pkg/resourcehandlers/pg/pg.go
Fix package & variable name collision
Fixes #
```noteworthy user
None
```
=> Fix package & variable name collision

cmd/app/factory.go
Removes headers filter as Last-Modified does not reflect changes in subfolders
Fixes #
```noteworthy user
Fixes an issue with cache invalidation as new content in the subfolders was not displayed
```
=> Removes headers filter as Last-Modified does not reflect changes in subfolders

diff_check.sh
Added script for consistency checking
Use --help to view details 
```noteworthy developer
Added script for consistency checking
```
=> Consistency script

README.md
Added flag descriptions in README
```noteworthy developer
Added flag descriptions in README
```
=> Added flag descriptions in README

.ci/integration-test, cmd/app/cmd.go, cmd/app/factory.go, cmd/app/manifest.go, integration-test/manifest.yaml, pkg/api/parser.go, pkg/api/parser_test.go, pkg/resourcehandlers/git/git_resource_handler.go, pkg/resourcehandlers/git/git_resource_handler_test.go, pkg/resourcehandlers/github/github_resource_handler.go, pkg/resourcehandlers/pg/pg.go
Vars and flags refactor
```improvement developer
Vars and flags refactor
```
=> Vars and flags refactor

README.md, diff_check.sh, docs/cmd-ref/docforge.md, docs/cmd-ref/docforge_completion.md, docs/cmd-ref/docforge_gen-cmd-docs.md, docs/cmd-ref/docforge_version.md
Documentation for refactored flags updated
```noteworthy developer
Documentation for refactored flags updated
```
=> Documentation for refactored flags updated

cmd/app/cmd.go, cmd/app/factory.go, pkg/api/parser.go, pkg/reactor/manifest_resolver.go
Cleans some of the TODOs
```improvement developer
Todo cleanup
```
=> Todo cleanup

pkg/reactor/content_processor.go
:v: Emoji link fix
```improvement developer
NONE
```
=> Emoji link fix

integration-test/tested-doc/merge-test/secondManifest.yaml, pkg/manifest/manifest.go
Fix manifest bug
```noteworthy user
NONE
```
=> Fix manifest bug

pkg/writers/fswriter.go
Minor indexmd fix 
```noteworthy user
NONE
```
=> Minor indexmd fix

cmd/app/flags.go, pkg/reactor/content_processor.go, pkg/reactor/reactor.go
Toggle link validation
```noteworthy user
NONE
```
=> Toggle link validation

cmd/app/types.go, integration-test/expected-metadata/mainTree/markdown-tests/file1.md.json, pkg/manifest/export_test.go, pkg/manifest/manifest.go, pkg/manifest/manifest_types.go, pkg/manifest/node.go, pkg/manifest/options.go, pkg/readers/link/resource_link.go, pkg/readers/repositoryhosts/githubhttpcache/github_http_cache.go, pkg/readers/repositoryhosts/registry.go, pkg/readers/repositoryhosts/repositoryhostsfakes/local_filesystem_registry.go, pkg/workers/document/document_worker.go, pkg/workers/document/document_worker_test.go, pkg/workers/document/frontmatter/frontmatter.go, pkg/workers/document/frontmatter/frontmatter_test.go, pkg/workers/document/job.go, pkg/workers/downloader/downloader.go, pkg/workers/downloader/job.go, pkg/workers/githubinfo/github_info.go, pkg/workers/githubinfo/github_info_test.go, pkg/workers/githubinfo/job.go, pkg/workers/linkresolver/link_resolving.go, pkg/workers/linkresolver/link_resolving_test.go, pkg/workers/linkvalidator/validator.go, pkg/workers/taskqueue/taskqueue.go, pkg/workers/taskqueue/taskqueue_collection.go
Fix checks
```noteworthy user
NONE
```
=> Fix checks

.reuse/dep5, CONTRIBUTING.md, LICENSE, LICENSES/Apache-2.0.txt, LICENSES/BSD-2-Clause.txt, LICENSES/BSD-3-Clause.txt, LICENSES/CC-BY-4.0.txt, LICENSES/ISC.txt, LICENSES/MIT.txt, LICENSES/MPL-2.0.txt, README.md
* Created `CONTRIBUTING.md` file
* Created/Updated `LICENSE` file
* Created/Updated `.reuse/dep5` file
* Created/Updated `LICENSES` folder
* Added badge for reuse compliance in `README.md` file and registered repo with REUSE API
**Additional information**
To keep this repository compliant, CODEOWNERS must maintain their third party dependencies in the vendor folder using `.reuse/dep5` file. To prevent constant maintenance effort, it is **highly recommended** to remove the `vendor` folder. In this case no third party dependencies of the vendor folder must be maintained anymore!
=> Make repo compliant

pkg/manifest/manifest.go, pkg/readers/link/resource_link.go, pkg/readers/repositoryhosts/githubhttpcache/github_http_cache.go, pkg/readers/repositoryhosts/githubhttpcache/github_http_cache_test.go, pkg/workers/document/job.go, pkg/workers/document/tests/expected_target.md, pkg/workers/document/tests/expected_target2.md, pkg/workers/downloader/downloader.go, pkg/workers/linkresolver/link_resolving.go
Fixes #
```noteworthy developer
NONE
```
=> Add uncommited changes that should have been in v0.43.0

integration-test/expected-metadata/mainTree/markdown-tests/file1.md.json
Fixes integration test
Fixes #
```noteworthy user
NONE
```
=> Fix integration-test

.ci/pipeline_definitions
Fixes #
```noteworthy user
NONE
```
=> Make e2e use same image as integration-test

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/tests/manifests/colliding_dir_frontmatters.yaml
Fixes https://github.com/gardener/docforge/issues/326
```noteworthy user
NONE
```
=> Fix colliding dir frontmatter

cmd/app/exec.go, cmd/app/flags.go, cmd/app/types.go, pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/node.go, pkg/manifest/tests/manifests/aliases.yaml, pkg/manifest/tests/results/aliases.yaml, pkg/registry/registry.go, pkg/registry/repositoryhost/github_http_cache_test.go, pkg/workers/document/document_worker.go, pkg/workers/document/document_worker_test.go, pkg/workers/document/job.go, pkg/workers/linkvalidator/validator.go
- Introduce build-wise and node-wise link validation skip
- Add improved alias logic
- Minor bugfix
Fixes #
```noteworthy user
NONE
```
=> Minor changes

.ci/pipeline_definitions, Makefile, README.md
Fixes #
```noteworthy user
```
=> Migrate remaining GCR occurrences to GAR

pkg/registry/repositoryhost/github_http_cache.go
Fixes #
```noteworthy user
NONE
```
=> Skip non-tree and non-blob files when loading repo

pkg/manifest/manifest.go
Fixes #
```noteworthy user
NONE
```
=> Minor enhancement

.ci/e2e, Makefile, cmd/gendocs/gendocs.go, integration-test/expected-tree/mainTree/html-tests/fileTree/innerDir/testedHTMLFile5.md, integration-test/expected-tree/mainTree/html-tests/fileTree/testedHTMLFile3.md, integration-test/expected-tree/mainTree/html-tests/fileTree/testedHTMLFile4.md, integration-test/expected-tree/mainTree/html-tests/testedHTMLFile2.md, integration-test/expected-tree/mainTree/markdown-tests/fileTree/innerDir/testedMarkdownFile5.md, integration-test/expected-tree/mainTree/markdown-tests/fileTree/testedMarkdownFile3.md, integration-test/expected-tree/mainTree/markdown-tests/fileTree/testedMarkdownFile4.md, integration-test/expected-tree/mainTree/markdown-tests/testedMarkdownFile2.md, integration-test/expected-tree/mainTree/multiformatMerge.md, integration-test/expected-tree/merge-node/level1-container-node1/fileD.md, integration-test/expected-tree/merge-node/level1-container-node1/level2-container-node1/fileD.md, integration-test/expected-tree/merge-node/level1-container-node1/level2-container-node1/level3-container-node1/fileD1.md, integration-test/expected-tree/merge-node/level1-container-node1/level2-container-node1/level3-container-node1/fileD2.md, integration-test/expected-tree/merge-node/level1-container-node1/level2-container-node1/level3-container-node1/fileY1.md, integration-test/expected-tree/merge-node/level1-container-node1/level2-container-node1/level3-container-node1/fileY2.md, integration-test/expected-tree/merge-node/level1-container-node1/level2-container-node2/fileD.md, integration-test/expected-tree/merge-node/level1-container-node1/level2-container-node2/fileY.md, integration-test/expected-tree/merge-node/level1-container-node2/fileD.md, integration-test/expected-tree/merge-node/level1-container-node2/fileY.md, pkg/manifest/manifest.go, pkg/registry/repositoryhost/github_http_cache_test.go, pkg/registry/repositoryhost/local.go, pkg/workers/document/frontmatter/frontmatter.go, pkg/workers/document/markdown/link_modifier.go, pkg/workers/document/markdown/parser_test.go, pkg/workers/document/markdown/specs_test.go, pkg/writers/fswriter_test.go
Improves code maintainability and simplicity.
Fixes #336 
N/A
```noteworthy user
`make lint` and `make lint-fix` introduced
```
=> Add default `golangci-lint`

pkg/manifest/manifest.go
=> Print collided node and rename `loadManifestStructure`

pkg/workers/document/document_worker.go
=> `fullContent[0].docAst` could be nil

.ci/update-release.py
Fixes #
```bugfix developer
adjust to incompatible changes in cc-utils
```
=> Fix and refactor

.ci/pipeline_definitions
=> Temporary disable e2e

.ci/update-release.py
pass filelike object to asset-upload
Fixes #
```bugfix developer
fix regression from previous refactoring in update-release-script
```
=> fix regression from previous refactoring

.ci/pipeline_definitions
Adds enabled e2e to CI pipeline.
Finalizes #389 
N/A
```noteworthy user
NONE
```
=> enable e2e in pipeline

task.sh
Inspired by https://github.com/golang/go/commits/master/ 
For example if we have changes 
```
pkg/manifest/manifest.go
pkg/manifest/tests/manifests/manifest.yaml
```
`make task m="Fixed bug"` will create a commit with message `pkg/manifest: Fixed bug`
And 
```
pkg/manifest/manifest.go
pkg/manifest/tests/manifests/manifest.yaml
pkg/registry/repositoryhost/resource_url.go
```
`make task m="Fixed bug"` will create a commit with message `pkg: Fixed bug`
This is very useful as:
- when reviewing the reviewer instantly understands the locality and scope of the change by the commit
- can serve as a hint for a need for refactoring. Code that changes together needs to be placed relatively close.If we constantly have commit messages `pkg: ...` this means that …
=> task.sh: Add package of changes in commit message

.ci/e2e, test/e2e/diff.sh
Redacts the relative path to the docforge repo in `diff.sh`
N/A
NONE
```noteworthy user
NONE
```
=> Edit path to repo in diff.sh

test/README.md
This PR adds a document describing the testing goals of the docforge repository
```noteworthy user
NONE
```
=> Add testing goals

pkg/link/link.go, pkg/link/link_test.go, pkg/must/assertions.go, pkg/workers/linkresolver/link_resolving.go
Inspired by `regex.MustCompile` и `template.Must`
```noteworthy user
NONE
```
=> Introduce `must.Succeed`

pkg/internal/must/assertions.go, pkg/manifest/manifest.go
This PR is a setup for manifest plugins
```noteworthy user
NONE
```
=> Setup for manifest plugins

cmd/app/cmd.go, cmd/app/exec.go, cmd/app/flags.go, cmd/docsy/option.go, docs/plugin/docsy.md, pkg/manifest/manifest.go, pkg/manifestplugins/docsy/plugin.go, pkg/manifestplugins/interface.go, pkg/registry/repositoryhost/resource_url.go
This PR introduces the docsy plugin `Edit this page`
```noteworthy user
NONE
```
=> Docsy plugin edit this page

pkg/nodeplugins/markdown/document/document_worker.go, pkg/nodeplugins/markdown/document/document_worker_test.go, pkg/nodeplugins/markdown/document/frontmatter/frontmatter.go, pkg/nodeplugins/markdown/document/frontmatter/frontmatter_test.go, pkg/nodeplugins/markdown/document/tests/docs/expected_target.md, pkg/nodeplugins/markdown/document/tests/docs/target.md
This PR is a precondition for the 404.js plugin
```noteworthy user
NONE
```
=> Move frontmatter to node

pkg/manifestplugins/interface.go
=> Describe the value of a no-op NodeTransformation

cmd/app/exec.go
This PR is a setup for multistage runs necessary for the 404.js plugin
```noteworthy user
NONE
```
=> Setup for multistage runs

task.sh
=> task.sh: Add [tested] prefix to repo scoped changes

cmd/app/cmd.go, cmd/app/exec.go, cmd/app/flags.go, cmd/persona/option.go, docs/plugin/persona.md, pkg/manifest/manifest.go, pkg/manifestplugins/persona/plugin.go, pkg/manifestplugins/persona/plugin_test.go, pkg/manifestplugins/persona/tests/manifests/persona_filtering.yaml, pkg/manifestplugins/persona/tests/results/persona_filtering.yaml, test/e2e/docforge_config.yaml
This PR introduces the Persona plugin.
Part of #401
N/A
```noteworthy user
There is now a `Persona` plugin, which separates content based on persona choice.
```
=> Add `Persona` plugin

cmd/app/exec.go, pkg/manifest/manifest.go, pkg/manifest/node.go, pkg/nodeplugins/persona/persona-filtering.json.tpl, pkg/nodeplugins/persona/plugin.go, pkg/nodeplugins/persona/plugin_test.go, pkg/nodeplugins/persona/tests/manifests/persona_filtering.yaml, pkg/nodeplugins/persona/tests/results/persona_filtering.yaml
**Note**: The following tasks need to be done in a following PR
1. Update `pkg/nodeplugins/persona/persona-filtering.json.tpl` if nessesary
2. Not use `p.Process(allNodes[0])` but `p.Process(allNodes[x])` where `allNodes[x]` is a node without source, and having a name `persona-filtering.js`(or something like this)
3. Improve test to check what content will be written
```noteworthy user
NONE
```
=> Introduce persona nodeplugin

pkg/nodeplugins/persona/plugin.go, pkg/nodeplugins/persona/plugin_test.go, pkg/nodeplugins/persona/tests/manifests/persona_filtering.yaml, pkg/nodeplugins/persona/tests/results/persona-filtering.js, pkg/nodeplugins/persona/tests/results/persona_filtering.yaml
1. Update of pkg/nodeplugins/persona/persona-filtering.json.tpl
2. Fix bubbling up logic for parent paths
3. Improve test to check what content will be written
Related to https://github.com/gardener/docforge/pull/419
cc @Kostov6 
```noteworthy user
NONE
```
=> Improve `persona` nodeplugin

pkg/manifest/manifest.go, pkg/manifest/manifest_test.go, pkg/manifest/tests/manifests/colliding_dir_frontmatters.yaml, pkg/manifestplugins/alias/tests/manifests/aliases.yaml, pkg/manifestplugins/alias/tests/results/aliases.yaml, pkg/manifestplugins/docsy/plugin_test.go, pkg/manifestplugins/docsy/tests/manifests/dir.yaml, pkg/manifestplugins/filetypefilter/plugin.go, pkg/manifestplugins/filetypefilter/plugin_test.go, pkg/manifestplugins/filetypefilter/tests/manifests/unsupported_file_format.yaml
=> Fix filter flake

integration-test/expected-tree/mainTree/html-tests/file1.md, integration-test/expected-tree/mainTree/html-tests/fileTree/innerDir/testedHTMLFile5.md, integration-test/expected-tree/mainTree/html-tests/fileTree/testedHTMLFile3.md, integration-test/expected-tree/mainTree/html-tests/fileTree/testedHTMLFile4.md, integration-test/expected-tree/mainTree/html-tests/testedHTMLFile2.md, integration-test/expected-tree/mainTree/markdown-tests/file1.md, integration-test/expected-tree/mainTree/markdown-tests/fileTree/innerDir/testedMarkdownFile5.md, integration-test/expected-tree/mainTree/markdown-tests/fileTree/testedMarkdownFile3.md, integration-test/expected-tree/mainTree/markdown-tests/fileTree/testedMarkdownFile4.md, integration-test/expected-tree/mainTree/markdown-tests/testedMarkdownFile2.md, integration-test/expected-tree/mainTree/multiformatMerge.md, pkg/nodeplugins/markdown/linkresolver/link_resolving.go
Removes downcasing of links in order to fix possible irregularities with resolving links for referenced resources that contain upper case letters.
Fixes #427 
cc @Kostov6 
```noteworthy user
NONE
```
=> Fix irregularities caused by downcasing of links
