pkg/reactor/content_processor.go
pkg/reactor/content_processor_test.go

Fix failing processing of links that contain `src=` or `href=`
Fixes #81 
```improvement user
Fixed an issue with failure to process documents with markdown links, which contain `src=` or `href=`
```

fix wrong handling of markdown links with src= or href= in URL

---

pkg/markdown/links.go
pkg/markdown/links_test.go
pkg/markdown/parser/links.go

Fixes an issue with missing offset in the _components_ of a markdown link that is changed, similar to how its subsequent siblings are offset.
Fixes an issue with wrong test if original and proposed text/title are different that prevented them to be changed when they were.
Fixes #83 
Fixes #84 
```improvement user
Fixed an issue with failing updates of text and destination components of markdown links when they are longer than the original ones. Updated text in these cases used to overlap the next component(s) because they were not offset with the changed length.
```
```improvement user
Fixed an issue with text or title of markdown links not being updated silently.
```

fix md link text and destination updates

---

pkg/resourcehandlers/github/resource_locator.go
pkg/resourcehandlers/github/resource_locator_test.go

Add support for GitHub `commit(s)` resource type
Fixes #90
```improvement user
Fixes failures to forge document bundles with links to GitHub commit(s) resources.
```

support for GitHub commit(s) resource links

---

cmd/app/cmd.go
cmd/app/config.go

Parameterized manifests help significantly reduce redundancy and with that error proneness and make automation easier.
With this PR, we start processing the manifest files as [Go templates](https://golang.org/pkg/text/template/) before starting the docs forging process.
This actually opens up for far more than using variables in the manifest. Now it can be dynamically constructed and scripted to a great extent. 
The variables supplied to the manifest template are provided with a `"string-name=string-value"` map flag `--variables`. The limitations and inconvenience of supplying more complex structure as variables via the CLI flags is the only limitation here. As soon as we provide a config file alternative this will be no longer a constraint. Another …

Manifests as Go templates

---

go.mod
go.sum
pkg/api/validate.go
pkg/reactor/content_processor_test.go
pkg/reactor/reactor.go
pkg/reactor/reactor_test.go
pkg/resourcehandlers/fs/fs.go
pkg/resourcehandlers/fs/fs_test.go
pkg/resourcehandlers/github/github_resource_handler.go
pkg/resourcehandlers/github/github_resource_handler_test.go
pkg/resourcehandlers/github/integration_test.go
pkg/resourcehandlers/resource_handlers.go
pkg/resourcehandlers/resource_handlers_test.go

Adds support for modularization of the Docforge manifest files. This enables construction of manifests from smaller, potentially reusable manifests, which ultimately lowers the complexity in enormous structures. Modules are imported with a `NodesSelector.Path` referencing a manifest. The manifest can reside on the local file system or at GitHub.
Fixes #55 
TODOs:
- https://github.com/gardener/docforge/pull/87/files#r518782949 
- https://github.com/gardener/docforge/pull/87/files#r518793265
- https://github.com/gardener/docforge/pull/87#pullrequestreview-525183045
```noteworthy user
Support for modules is introduced to minimize the complexity and maximize the …
```

add support for including modules

---

cmd/app/cmd.go

Fixes #103 
```noteworthy user
Docforge main command usage is now shown only on flags/cmd/args error.
```

Silence command usage on errors except those that require it for reference

---

pkg/hugo/processor.go
pkg/markdown/html_links.go
pkg/markdown/links.go
pkg/markdown/links_test.go
pkg/markdown/parser/document.go
pkg/markdown/parser/links_test.go
pkg/markdown/parser/types.go
pkg/reactor/content_processor.go

The logic for parsing HTML links for rewriting is duplicated in hugo processor and reactor.nodeContentProcessor. This duplication proved hard to maintain. it can an should be generalized similar to handling MD links and that's what this PR does. 
Fixes #101 
Golang features a builtin HTML parser that does the job of finding links properly. However when it comes back to writing back its renderer does that on best effort and can introduce side-effects as we had with the markdown parsers. On the other hand the regex based solution is missing context on a match (can't tell tag, title, text) and updates are feasible only on the destination component, which we do.    
Perhaps a hybrid …

Common html link parser

---

cmd/app/completion.go

The help format of the `docforge completion` is not markdown friendly and the product of `docforge gen-cmd-ref` for it is not very readable. This PR improves that.

improve the help for cli ref md

---

pkg/hugo/fswriter.go

bugfix 
Fixes #109
```improvement user
"Multiple peer nodes with property index: true detected in ..." is no longer thrown when there is 1 or less nodes declaring `index:true` property and building with `--hugo` flag.
```

fix false multiple peer nodes with property index error

---

pkg/reactor/gitinfo_controller.go
pkg/resourcehandlers/fs/fs.go
pkg/resourcehandlers/github/github_resource_handler.go
pkg/resourcehandlers/github/gitinfo.go

Bugfix
Fixes #114 
```improvement user
Using docforge with `--github-info-destination` flag failed with nil pointer reference panic when all commits for a file referenced by a node source in the structure were internal. This is fixed now.
```

Do not panic when all git commits are internal

---

.ci/build
pkg/processors/frontmatter.go
pkg/processors/frontmatter_test.go

Currently the implementation merges frontmatter defined inside the node and the document. 
Fixes #116
```noteworthy user
If both document and a node referencing it as source define front-matter, they will be merged and where there are conflicting keys the node front-matter has priority. Note that this is a temporary solution and may change.
```

prevent reduntant frontmatter property: "title"

---

pkg/reactor/content_processor.go

The document byte array produced after processing HTML links was ignored. This is fixed now.
Fixes #118 
```improvement user
Fixed a problem with HTML links not getting updated to absolute or to downloaded resource references in cases when they needed to.
```

Fix document not updated after HTML links update

---

pkg/reactor/build.go
pkg/reactor/gitinfo_controller.go

- Moves the rwLock's `Lock` and deferred `Unlock` to the proper place in the `updateContributors` function.
- Added a few v=6 level logs to have the read/writes related to the github info operations not that silent.
- Early exit for container nodes (sanity check). Git info is gathered only for document nodes.
Fixes #123 
Bug introduced with gardener/docforge#122

Fix deferred unlock miss

---

cmd/app/cmd.go
pkg/jobs/jobs.go
pkg/jobs/jobs_test.go
pkg/reactor/content_processor.go
pkg/reactor/content_processor_test.go
pkg/reactor/download_controller.go

- Makes sure `resolveLinks` records also referrer and (original) reference and then these are used as additional context when an error occurs
- Now download controller registers not only downloaded sources, but also the tasks that requested that (`source: []*DownloadTask`) and supplies info for all referrers and references that were affected by an error using this.
- the multierror result is less than ideal but formatting is not part of this PR
- Fixes a couple of typos.
Use `-v=6` to test
Fixes #125
Fixes #126
```noteworthy user
Logs for download failures now include more context to trace them back to the reference link and fix it if that is the reason. 
```
```improvement user
Fixed the list of …
```

add more context to download logs/errs

---

cmd/app/factory.go

Adds http logging middleware wrapper around the http client transport.
```
I1122 21:50:05.805781  313799 factory.go:192] HTTP GET https://api.github.com/repos/gardener/documentation/git/blobs/791942ffd90f56311b72beb1b8729d4028b028c7 200 OK
I1122 21:50:05.894353  313799 factory.go:192] HTTP GET https://api.github.com/repos/gardener/documentation/git/trees/master?recursive=1 200 OK
```
Fixes #128 
```noteworthy user
With verbosity flag >= 6 enabled (`-v=6`), now logs contain also HTTP logs. The logs are simple and consist of the request method, URL and response status.
```

add http log

---

pkg/hugo/processor.go
pkg/markdown/html_links.go
pkg/reactor/content_processor.go

- Adds sanity check on parsed links before processing them and skips processing if no destination is found
- Fixes incorrect usage for multierror that stored only the last entry in the multierror object
Fixes #130 
```improvement user
Logs had entries like `-> abc`, which were result from text, incorrectly parsed text as links. Such incorrectly parsed links will no longer be processed as links.
```
```improvement user
Fixed reported errors from command execution. Previously many were logged but the few were reported as errors summary report at the end of the command execution.
```

add sanity check for links

---

cmd/app/manifest.go

Adds Split as function that could be used in templates to split strings. 
```
{{ result := Split "a,b,c" "," }}
```
result is going to equal to the array result=[a,b,c] 
For more details about Split functions: https://golang.org/pkg/strings/#Split
Fixes #
```noteworthy user
NONE
```

add strings.Split as function in templates

---

Dockerfile

This is in order to prevent multiple hits to the Docker's registry rate limits.

Use alpine docker image from gcr.io registry

---

pkg/resourcehandlers/github/github_resource_handler.go
pkg/resourcehandlers/github/github_resource_handler_test.go
pkg/resourcehandlers/github/resource_locator.go

Switches to using `ResourceLocator` `SHAAlias` instead of parsing the `Path` property.
Fixes #133
```improvement user
Fix wrong additions of a version segment in url paths that do not have such type of segment, like pulls/wiki etc.
```

Fixes uses of version segment in github urls

---

pkg/resourcehandlers/github/github_resource_handler.go
pkg/resourcehandlers/github/github_resource_handler_test.go

With the current implementation nodes that have child nodes are considered empty and removed, this may lead to panic of type:
`panic: runtime error: slice bounds out of range [4:2]`
This PR changes the strategy of removing such nodes by creating a new list without the "empty" nodes and later overwriting the existing. 
Fixes #
I've added a unit test that is covering this case scenario.

bug fix for deleting multiple empty tree nodes

---

pkg/markdown/parser/autolinks_parse.go
pkg/markdown/parser/autolinks_parse_test.go
pkg/markdown/parser/links_parse_test.go
pkg/markdown/parser/parser.go

Docforge fails to parse links that are inside code span blocks similar to `http://localhost:8080`

fix parsing of links inside code span

---

pkg/jobs/jobs.go
pkg/jobs/jobs_test.go
pkg/reactor/build.go

During the download of documents or resources that they refer to, the program is prone to errors (e.g "Resource not found"). Because of the concurrency model of Docforge, to collect these errors, from multiple workers a list of go channels is used. To synchronize the creation of error channels from the workers and to prevent multiple read/writes to the list, a read/write lock is added to the list.
**Fixes** #146
```noteworthy user
Fixes a synchronization problem that was observed when having multiple errors during document download.
```

Synchronize error propagation to prevent program freeze

---

pkg/markdown/parser/links_parse.go
pkg/markdown/parser/links_parse_test.go

Skip early, during parse, links that do not meet minimal criteria for valid links.
Fixes #136

Skip parsing invalid links

---

pkg/api/nodes.go
pkg/reactor/content_processor.go
pkg/reactor/reactor.go

Adds a ghost root node and configures the downstream hierarchy so that that it becomes parent to the members of the Structure array of Nodes and the upstream hierarchy so that Nodes in the structure array have it set as its parent.
This is a minimal intervention change to fix the issue that the nodes in the Structure array had no common parent and traversal algorithms were scoped within each of these node's hierarchy, but could not reach out to peer structure nodes. That affects the computation of relative links. 
As a by-product of enforcing a common root node correctly, now top-level `NodesSelector`'s hierarchy is preset correctly.
Fixes #150 
```improvement user
Fixed an issue with simple …
```

add ghost root node to structure direct children

---

pkg/hugo/fswriter.go

Fixes the comparison between actual file names and the ones specified in the flag
Adds removal of the original file upon rename situation.
Fixes #153
```improvement user
Fixes a bug when using the `--hugo-section-files` that did not result in rename of matching argument file names as expected.
```

Fixes file comparison and rename

---

pkg/markdown/links.go
pkg/markdown/parser/document.go
pkg/markdown/parser/links.go
pkg/markdown/parser/links_test.go
pkg/markdown/parser/types.go

Fixes positions offset during link removal. 
Fixes links slice removals on the fly.
Propagates update callback errors.
Fixes #158 
```noteworthy user
Fixes a runtime error when multiple links match a rewrite rule to be removed completely from a document.
```

fix link removal

---

go.mod
go.sum
pkg/processors/processor.go
pkg/reactor/document_worker.go
pkg/resourcehandlers/github/github_resource_handler.go
pkg/resourcehandlers/github/github_resource_handler_test.go
pkg/resourcehandlers/github/resource_locator.go
pkg/resourcehandlers/resource_handlers.go

Introduces a simplified key, based on the resource locators, that is used for caching the GitHub resources. The new key is host agnostic meaning (github.com or raw.githubusercontent.com are in the end the same) 
Fixes an issue that was preventing linked resources with "?raw=true" to be discovered in the cache
```noteworthy user
```

cache uses a key generated using ResourceLocator

---

go.sum
pkg/reactor/content_processor.go
pkg/resourcehandlers/fs/fs.go

Fixes the resolution of relative links, when the document is referencing directories or tree objects, by transforming them to absolute links. For example, a link of type ../content/dir will be transformed to its absolute path. In the case of GitHub that would be https://github.com/org/repo/tree/master/content/dir.
Fixes #15 
I would like to add the unit tests after PR #108 is merged. Because I will use the test resource handler introduced with it.
```noteworthy user
```

fix absolute links to tree/dir objects

---

cmd/app/factory.go
pkg/hugo/processor.go
pkg/hugo/processor_test.go
pkg/processors/frontmatter.go
pkg/processors/frontmatter_test.go

Considers parent name when node is section index file. Removes common file name delimiters and .md file extension.
Fixes a couple of issues found in hugo and front matter processors.
Fixes #164
```noteworthy user
The `title` front-matter property is generated smarter now. For index nodes it takes the name of the parent node. Name delimiters `_`  and `-` are replaced with space, `.md` extension is removed and finally the string is converted to title case.   
Example 1: A node with name `abc_def-1.md` gets `title: Abc Def 1`    
Example 2: A node with name `README.md` and parent node name `concepts` gets `title: Concepts`, assuming that `README.md` has been specified as index file name via the …
```

Improve front-matter titles

---

pkg/git/types.go
pkg/resourcehandlers/github/gitinfo.go
pkg/resourcehandlers/github/testdata/test_format_00_out.json

Adds git commits `html_url` as `weburl` property in files' gitinfo.
Example:   
With html_url in commit history like that:
```yaml
{
"sha": "2a97450d964f39ee1b320fecd4c565f83f2590eb",
"node_id": "MDY6Q29tbWl0MTEzMDMwODQ1OjJhOTc0NTBkOTY0ZjM5ZWUxYjMyMGZlY2Q0YzU2NWY4M2YyNTkwZWI=",
"html_url": "https://github.com/gardener/documentation/commit/2a97450d964f39ee1b320fecd4c565f83f2590eb",
...
```
we construct weburl in gitinfo like that:
```yaml
{
...
"weburl": "https://github.com/gardener/documentation",
...
```
Fixes #165
```noteworthy user
A new proprty `weburl` added to files gitinfo. It is a URL that references the repository hosting the file for which the gitinfo has been created.
```

Add web url to files git-data

---

pkg/git/types.go
pkg/resourcehandlers/github/github_resource_handler.go

Amends the produced gitinfo with details from the resource locator for which the gitinfo is generated. 
Fixes #170
```noteworthy user
New properties `path`, `sha` and `shaalias` added to gitinfo generated for GitHub resources. The `path` property is the resource path in GitHub after resource type and its sha. `The `shaalias` property is the human readable tag/branch-name assigned to a sha (e.g. `master`). 
```

add GH resource details to git info

---

pkg/resourcehandlers/github/github_resource_handler.go

Skips tree entries that have no URL during transformation to` ResourceLocator`.
Fixes #173
```improvement user
Fixes a runtime error when using manifests that reference GitHub repositories with submodules.
```

Skip TreeEntry objects without URL

---

cmd/app/cmd.go
cmd/app/factory.go
go.mod
go.sum
pkg/reactor/content_processor.go
pkg/reactor/document_worker.go
pkg/reactor/manifest_resolver.go
pkg/reactor/manifest_resolver_test.go
pkg/reactor/reactor.go
pkg/resourcehandlers/github/github_resource_handler.go
pkg/resourcehandlers/testhandler/test_resource_handler.go

It doesn't allow to import a module that is importing the current structure.
It detects a circular dependencies and prevents never ending cycle.
Adds a simple TestResourceHandler that could be used to mock the implementation of the ResourceHandler interface.
Fixes leftover todo from PR #87, and Issue #94
I left a TODO in the cmd.go and I would like to discuss what is the best approach here.
```noteworthy user
Circular dependencies are prevented with an error.
```

break cycling dependenciec with a warning 

---

cmd/app/cmd.go
cmd/app/factory.go
cmd/app/gendocs.go
cmd/configuration/configuration.go
cmd/configuration/types_configuration.go
go.mod
go.sum
pkg/resourcehandlers/git/git_resource_handler.go

Adds option to use a configuration file for providing Docforge with authentication to Git. 
The default location where Docforge looks for the config file is under `~/.docforge/config`.
This location can be overridden by the env var `DOCFORGECONFIG`
The config file should be in `yaml` format.
Example:
```yaml 
sources:
- host: github.com
credentials:
username: swilen-iwanow
oauthToken: a1de4075ffbffa6a5bb6bbedb3f55173fdb0d8cb
- host: github.enterprise.com
credentials:
username: internal_user
oauthToken: b25809e309dc01aa8437f6a4ae5e51bf5177e554
- host: github.enterprise2.com
credentials:
username: internal_user
oauthToken: 9912812c03a44011e845a958725efe99edd5291e
```
**Release …

use configuration file for auth

---

pkg/resourcehandlers/git/git_resource_handler.go
pkg/resourcehandlers/git/repository.go

Adds more intelligent lock on the git repositories in case multiple workers try to execute operations over them.
Fixes #
```noteworthy user
```

add Repository type for better concurrent ops with git repos

---

cmd/app/cmd.go
cmd/app/factory.go
cmd/configuration/types_configuration.go
pkg/resourcehandlers/fs/fs.go
pkg/resourcehandlers/fs/fs_test.go
pkg/resourcehandlers/git/git_resource_handler.go
pkg/resourcehandlers/git/repository.go
pkg/resourcehandlers/utils/gitlog.go

1. Use Git for building info data for each documentation file.
2. Add the possibility to configure local mappings inside the config file you are using for example:
`~/.docforge/config`:
``` yaml
sources:
- host: github.com
credentials:
username: swilen-iwanow
oauthToken: ****TOKEN****
resourceMappings:
https://github.com/garedener/documentation/blob/master/docs/documentation/document1.md: /Users/swilen/git/github.com/garedener/documentation/docs/documentation/document1.md
```
There are three options for providing local mapping: 
a. Repository
```yaml
resourceMappings:
https://github.com/garedener/documentation: /Users/swilen/git/github.com/garedener/documentation
```
b. Folder 
```yaml
resourceMappings: …
```

use git for source info data; add local mappings

---

cmd/app/cmd.go
cmd/app/cmd_test.go
cmd/app/factory.go
cmd/configuration/types_configuration.go

Adds support for Hugo BaseURL (--hugo-base-url), pretty URLs, and section files configuration inside the Docforge config file. 
1.`~/.docforge/config`:
```yaml
hugo:
baseURL: /base/url
sectionFiles: ["a", "b.md"]
prettyURLs: true
```
Note that when you have the previous example in your config you are not obligated to specify the --hugo flag either.
Plus you can specify only 
2.`~/.docforge/config`:
```yaml
hugo:
enabled: true
```
without `hugo.baseURL`, Docforge will start behaving as it would when --hugo is specified.
Motivation:
Using GitBash on Windows for working with bash scripts and Docforge in combination leads to errors when providing the `--hugo-base-url` flag when the link begins with `/` (backslash). Mitigation to this scenario is using …

add hugo options to configuration file

---

go.mod
go.sum
pkg/api/types.go
pkg/reactor/links.go

Use hash function for generating names of referenced resources instead of UUID
Closes #183
@swilen-iwanow 
```noteworthy user
The default regex for generated names of referenced resources now includes `<resource-name>_<abs_url>.<etx>`
```

Use hash function for generating names of referenced resources

---

go.mod
go.sum
pkg/reactor/reactor.go
pkg/reactor/reactor_test.go

When there is a container node that contains two or more nodes with the same name a warning is displayed.
Fixes [#184](https://github.com/gardener/docforge/issues/184)
```improvement operator
When collisions with node names collide, a warning is displayed.
```

Detect node name collisions and throw an error

---

pkg/writers/fswriter.go

Currently there is an issues in file extensions under /data directory.
Sometimes  they have an extension `.md.json` and sometimes  just `.json`.
With this change all of the extensions under /data will be `.md.json`
Fixes #
```noteworthy user
None
```

Fix file extensions in /data

---

cmd/app/cmd.go
cmd/app/factory.go
go.mod
go.sum
pkg/hugo/fswriter.go
pkg/hugo/fswriter_test.go
pkg/hugo/hugo.go
pkg/reactor/manifest_resolver.go
pkg/reactor/manifest_resolver_test.go
pkg/reactor/reactor.go
pkg/reactor/reactor_test.go
pkg/resourcehandlers/fs/fs.go
pkg/resourcehandlers/fs/fs_test.go
pkg/resourcehandlers/testhandler/test_resource_handler.go
pkg/writers/dryRunWriter.go
pkg/writers/fswriter.go
pkg/writers/fswriter_test.go

**What this PR does / why we need it:**
There is an issue with filenames stored under **/data/** folder. When node has `index=true` property, git info content is not stored in **_index.md.json** as expected, but in **<node.Name>.json** instead.
Which issue(s) this PR fixes:
Fixes #
#191 
```noteworthy user
None
```

fix index rename issue

---

pkg/resourcehandlers/git/git_resource_handler.go
pkg/resourcehandlers/github/github_resource_handler.go

- The type of relative links that points to folders is changed from 'blob' to 'tree'
- Fit git resource handler to support '\' file separator
Fixes #
```noteworthy user
```

Fix the type of relative links & add win FS support to git resource handler

---

pkg/reactor/content_processor.go
pkg/reactor/document_worker.go
pkg/reactor/download_controller.go
pkg/resourcehandlers/git/git_resource_handler.go
pkg/resourcehandlers/git/repository.go
pkg/resourcehandlers/github/github_resource_handler.go
pkg/resourcehandlers/github/github_resource_handler_test.go
pkg/resourcehandlers/github/github_utils.go
pkg/resourcehandlers/github/resource_locator_cache.go

Verify the resource type of relative links ( blob | tree ):
- changes the type of the link if necessary
- if the link target resource does not exist, throws ErrResourceNotFound
Fixes #
```noteworthy user
```

Verify the resource type of relative links

---

.ci/integration-test

Add default values to the int test org and version variables
Fixes #
@dimitar-kostadinov 
```noteworthy user
None
```

Add default values to the int test org and version variables

---

pkg/resourcehandlers/git/repository.go

Git handler breaks at times when there are unstaged changes

checkout fix

---

cmd/app/cmd.go
cmd/app/factory.go

OAuth token is optional 
```noteworthy user
Docforge can run even without an OAuth token
In this configuration the rate limit is only 60
```

oauth token is optional

---

.ci/check-manifest

Do not use token in check-manifest
Fixes #
```noteworthy user
None
```

Do not use token in check-manifest

---

pkg/processors/frontmatter.go
pkg/reactor/document_worker.go
pkg/reactor/reactor.go

Add more information in some errors
Fixes #
```noteworthy user
improve error handling with additional context
```

Add more information in some errors

---

.ci/check-manifest
.docforge/manifest.yaml
cmd/app/cmd.go
cmd/app/factory.go

Update /.docforge/manifest.yaml with relative paths
Adds option to defines config file location using DOCFORGE_CONFIG env
Fixes #
```noteworthy user
None
```

Update check-manifest to support relative paths in manifest.yaml

---

pkg/reactor/reactor_test.go
pkg/resourcehandlers/pg/pg.go
pkg/util/resource_info.go

Avoid unexpected EOF errors, using cache for 'docs' repo folders
Fixes #
```noteworthy user
None
```

Avoid unexpected EOF errors, using cache for 'docs' repo folders

---

pkg/reactor/content_processor.go

Fix bug with the document titles.
With the previous function if we try to parse `managed_seed` , the function returns `managed_see`.
Fixes #
```noteworthy user
The bug where the last letter of the node names is sometimes truncated is fixed
```

Fix bug with the document titles

---

.ci/pipeline_definitions
Dockerfile

This PR changes the base image for `docforge` container from `alpine` to [distroless](https://github.com/GoogleContainerTools/distroless). The process will now use a non root user for its execution. This will reduce the attack surface of the image.
It also updates go version to `1.17.12`.
Fixes #
```noteworthy user
Docforge is now built using go version `1.17.12`.
```
```noteworthy user
Docforge now uses `distroless` as a base container image.
```

Change base image from alpine to distroless and update go version to 1.17.12

---

.ci/build
.ci/pipeline_definitions
Dockerfile

This PR builds `arm64` binaries for `Linux` and `Darwin`.
Additionally, the the CI pipeline publishes multi-arch images with support for linux/amd64 and linux/arm64 now.
Fixes #280 
If I understood `.ci/update-release.py` script correctly the new binaries should be added to the release automatically.
```noteworthy user
Docforge release includes docforge binaries for `arm64` architecture on `Linux` and `Darwin` now.
Docker images are published with multi-arch support for `linux/amd64` and `linux/arm64` now.
```

Build Multi-Arch Images

---

pkg/markdown/link_modifier.go
pkg/markdown/link_modifier_test.go

Fix hugo parsing links ending with )
```improvement developer
Fix error in hugo when parsing links ending with )
```

Fix hugo parsing links near )

---

.ci/pipeline_definitions

Using go1.21 in pipeline_definitions
```noteworthy developer
NONE
```

Using go1.21 in pipeline_definitions

---

.ci/e2e

Image hashes are build from absolute urls so it is expected for them to be stable
Fixes #
```noteworthy user
NONE
```

Validate image hashes

---

.ci/pipeline_definitions

Currently, no OCM repository is specified for the component-descriptor traits. Hence, a standard repository is being used which does not match the desired one. Also, the `docforge` image is still being published to Google Container Registry (GCR), which is deprecated. That's why, this change sets the target repository in both cases to `europe-docker.pkg.dev/gardener-project/(snapshots|releases)`.
Fixes #
```noteworthy user
```

Publish component descriptor and image to GAR instead of GCR

---

.ci/docs-gen
.ci/pipeline_definitions
.ci/update-release.py

Since recently, the `_path` suffix is not appended to step outputs anymore ([ref](https://github.com/gardener/cc-utils/commit/7dfb6afed52e9a372640362174236992d3f74c64)). Hence, this change is a required follow-up for the changed behaviour.
Fixes #
```noteworthy user
```

Fix: rm _path suffix from input names and env vars

---

.ci/pipeline_definitions

Remove check-manifest and docs-gen steps
Part of https://github.com/gardener/docforge/issues/339
```noteworthy user
NONE
```

Remove check-manifest and docs-gen steps

---

.ci/e2e
.ci/integration-test
cmd/app/flags.go
pkg/workers/document/document_worker.go
pkg/workers/document/document_worker_test.go
pkg/workers/githubinfo/github_info.go
pkg/workers/githubinfo/github_info_test.go
pkg/workers/resourcedownloader/resourcedownloader.go
pkg/workers/resourcedownloader/resourcedownloader_test.go
pkg/writers/dryRunWriter.go
pkg/writers/fswriter.go
pkg/writers/fswriter_test.go
pkg/writers/writers.go
pkg/writers/writersfakes/fake_writer.go

Fixes https://github.com/gardener/docforge/issues/343
```noteworthy user
NONE
```

Handle IndexFileNames in Writer

---

Makefile
task.sh

Inspired by [Use git tactically](https://stackoverflow.blog/2022/12/19/use-git-tactically/#h1-941b6d3674fd0) this PR introduces `make task m="commit message"` that ensures the code compiles and runs tests before committing all the added files with the given commit message. These are the biggest benefits from `make task`:
- There are no commits that represent a partial functionality state. So when going over commits the reviewer doesn't need to keep mental track of previous partial states. That way all he needs to focus on is whether the current commit does what is described to do from the commit message
- This encourages people to split big tasks into smaller subtasks that are achievable and reviewable
- This discourages doing huge tasks that don't …

Introduce task make target that runs tests before committing the provided message

---

.ci/integration-test
integration-test/config

The idea of integration test is to catch any potentially breaking changes. This is done by linking the manifest to the master branch. Prior to this PR `integration-test` could load local docforge config file that through `resourceMappings` could overwrite integration-test file thus leading to a local pass of integration test and a ci/cd fail
```noteworthy user
NONE
```

Introduce integration-test config

---

pkg/manifest/manifest.go
pkg/manifest/tests/manifests/index_md_with_properties.yaml
pkg/manifest/tests/manifests/multisource.yaml

Defaulting files to `.md` does not provide any value so let's remove it at it is an implicit behavior. Files without extension were not skipped as they were defaulted to `.md`. When we don't have the defaulting logic let's just skip all files that are not `.md`
```noteworthy user
Remove defaulting of files to `md`. `fileTree` won't load files without `md `suffix
```

Remove defaulting of files to `md`. `fileTree` won't load files without md suffix

---

pkg/registry/repositoryhost/local.go

`Local.Accept()` no longer matches `gardener/gardener/` and any repository with `gardener/gardener-<rest of the repo name>/`
Fixes #345
N/A
```noteworthy user
Fixed resourceMapping for mappings with similar prefixes as gardener/gardener.
```

Fix issue in matching `gardener/gardener...` to `gardener/gardener/`

---

cmd/app/exec.go
cmd/app/flags.go
cmd/app/initilization.go
cmd/app/types.go

This PR adds a distinct `resource-website-path` flag that is the path in the website URL where resources will be accessed
```noteworthy user
NONE
```

Add `resource-website-path`

---

pkg/workers/taskqueue/taskqueue.go

This PR fixes a bug where when there are more than 1000 files docforge gets stuck
```noteworthy user
NONE
```

Temporary fix bug by increasing buffer size

---

.ci/e2e

Fix checking out empty `current_branch`

---

pkg/workers/document/document_worker.go

This PR inlines `processSource` and `docContent` in `process` function for better code readability 
```noteworthy user
NONE
```

[task] Inline `processSource` and `docContent` in `process`

---

pkg/manifest/node.go
pkg/workers/linkresolver/link_resolving.go
pkg/workers/linkresolver/link_resolving_test.go
pkg/workers/linkresolver/tests/baseline.yaml

When a document references a resource that appears multiple times in the manifest the link gets resolved pointing to the closest resource. Sometimes this resolution may not be desired.This PR introduces `linkResolution` node field that allows the user to overwrite this behavior by explicitly specifying the nodepath of the desired resource.
```noteworthy user
NONE
```

Introduce linkResolution node field

---

cmd/app/exec.go
cmd/app/flags.go
cmd/hugo/option.go
pkg/workers/linkresolver/link_resolving.go
pkg/workers/linkresolver/link_resolving_test.go
pkg/workers/linkresolver/tests/baseline.yaml

This PR implements `hugo-structural-dirs` flag. It is a list of directories that are part of the hugo bundle structure and should not be included in the resolved links.
```noteworthy user
NONE
```

Add `hugo-structural-dirs` flag

---

.ci/integration-test
README.md
cmd/app/flags.go
cmd/app/initilization.go
pkg/registry/repositoryhost/repository_host.go

Now Github credentials can only be provided through env vars for improved security
```noteworthy user
NONE
```

Replace `github-oauth-token-map` with `github-oauth-env-map`

---

pkg/link/link.go
pkg/link/link_test.go
pkg/manifest/node.go
pkg/workers/linkresolver/link_resolving.go

For example `/html/foo.html` should not receive a trailing `/` when hugo is enabled
```noteworthy user
NONE
```

Add a trailing slash only on hugo `.md` files

---

test/e2e/docforge_config.yaml

Adds config file in order for https://github.com/gardener/docforge/pull/393 to be able to checkout master and check diffs.
Part of #389
This PR is a prerequisite for https://github.com/gardener/docforge/pull/393
```noteworthy user
NONE
```

Add docforge_config.yaml for e2e test

---

pkg/link/link.go
pkg/manifest/manifest.go
pkg/manifest/manifest_test.go
pkg/manifest/node.go
pkg/registry/repositoryhost/resource_url.go
pkg/workers/document/document_worker.go
pkg/workers/linkresolver/link_resolving.go

Replace concatenation, `path.Join` and `fmt.Sprintf` with unified `link.Build` and `link.MustBuild`.
Fixes #378
N/A
```noteworthy user
NONE
```

Use `pkg/link` when building links for consistency

---

pkg/registry/repositoryhost/resource_url.go
pkg/registry/repositoryhost/resource_url_test.go

As the regex requires a backslash between the ref and resourcePath this PR makes this backslash optional
```noteworthy user
NONE
```

Support fileTree for root repo directory

---

pkg/internal/must/assertions.go

This PR improves assertion panic message to guide the reader how to handle the error. Broken assertions are programmer errors and therefore bugs to be fixed instead of a misuse of the tool (for example providing broken manifest URL which are not bugs but user errors)
```noteworthy user
NONE
```

Improve assertion panic message

---

cmd/app/exec.go
cmd/app/flags.go
pkg/manifest/manifest.go
pkg/manifestplugins/filetypefilter/plugin.go
pkg/manifestplugins/filetypefilter/plugin_test.go
pkg/manifestplugins/filetypefilter/tests/manifests/filtered_file_format.yaml
pkg/manifestplugins/filetypefilter/tests/results/filtered_file_format.yaml
test/e2e/docforge_config.yaml

Improves `filetypefilter` plugin in order not to error when met with an unsupported type and just ignore it. It will only error if a whole dir gets emptied by the filtering.
N/A
cc @Kostov6 
```noteworthy user
`filetypefilter` plugin will filter out files that aren't specified in the content formats field. It will only error if a whole dir gets emptied by the filtering.
```

Improve `filetypefilter` plugin

---

cmd/app/exec.go
pkg/manifestplugins/docsy/plugin.go
pkg/manifestplugins/docsy/plugin_test.go

Docsy plugin transformation needs to be executed after the Markdown plugin ones.
N/A
cc @Kostov6 
```noteworthy user
NONE
```

Add `Markdown` processor check to `Docsy` plugin

---

go.mod
go.sum
pkg/registry/repositoryhost/github_http_cache.go
pkg/registry/repositoryhost/github_http_cache_test.go
pkg/registry/repositoryhost/repository_host_test.go

Enables the use of a repository as a whole by using
``` 
fileTree: <link to repository>/tree/<branch>
```
Example: https://github.com/gardener/documentation/tree/master in order to use the master branch
Fixes #429 
N/A
```noteworthy user
Manifests now support imports of repositories using fileTree.
```

Enable import of a whole repository in manifests
